# Generated by Django 4.1.7 on 2023-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
    ]
