# Generated by Django 4.1.7 on 2023-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('books_issued_date', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('return_date', models.CharField(max_length=50)),
                ('book_status', models.CharField(max_length=50)),
            ],
        ),
    ]
